service: challange-zoluxiones

provider:
  name: aws
  runtime: nodejs14.x
  profile: deploy-dp
  region: us-east-1

functions:
  getFilm:
    handler: src/films/handler.listFilm
    events:
      - http:
          method: GET
          path: /film
          cors: true
      
      - http:
          method: GET
          path: /film/{idFilm}
          cors: true
          request:
            parameters:
              paths:
                idFilm: false

  getPlanets:
    handler: src/planets/handler.getAllPlanets
    events:
      - http:
          method: GET
          path: /planets
          cors: true
